services:
  - type: web
    name: lovable-merge-mate-server
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run render:start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 8080
